version: '3.7'

services:
  carrent-management:
    container_name: carrent-management
    image: fadimeaydiner/carrent_management_back_end:latest
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/carrent_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=changeme
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8181:8181"


